### ISSUE TITLE
Double Pipes

### ISSUE THREAD

**Issue by AyeshaKhan7** [AYJACKSON-ICS4U/codingchallenge-flappybird-challenge#1]
For some reason the code gives double pipes. Don't know how to fix it.

**Comment by jaip777** [comment]
So I looked over your code, and I did not find any errors at a glance. What I would do if I were you is go backwards, keep removing things that you had added one at a time and reload your index each time to see when the issue goes away (if it ever does). Hopefully, you at some point, it will go back to one pipe only, then you can follow along with Dan from there.

I would start by removing this first:

  if (frameCount % 40 == 0){
    pipes.push(new Pipe());
  }

and see that with just one pipe being pushed in the code if you get a double pipe issue or not. With this method of bug fixing it will hopefully allow you to isolate the problem code. If this doesn't work, then it might be a problem with your computer, or the browser you are opening your index with (try Mozilla firefox, I use that one for my index and have no issues. it also allows me to read my console).

hope that helps

**Comment by AyeshaKhan7** [comment]
Thanks a bunch!! I'll give it a try and let you know how it goes.

**Comment by AyeshaKhan7** [comment]
AHHHH!! I fixed it!!

I compared it to your code and it turns out that the html index was wrong!
